name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      MPLBACKEND: Agg

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (global, for flake8/pytest fallback)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Create test venv (.venv) and install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

      - name: Bootstrap tiny dataset and train inside .venv
        run: |
          mkdir -p data models
          printf '%s\n' \
            'text,label' \
            'Very good quality, I like it, great!,positive' \
            'Terrible, broken on arrival,negative' \
            'Amazing value for money,positive' \
            'Worst experience ever,negative' \
            'Fast delivery and excellent support,positive' \
            'Dirty and unacceptable restroom,negative' \
            > data/ci_reviews.csv

          # тесты ждут reviews_mapped.csv — подложим тот же мини-набор
          cp -f data/ci_reviews.csv data/reviews_mapped.csv

          . .venv/bin/activate
          python -m src.train \
            --data_path data/reviews_mapped.csv \
            --model_dir models \
            --model logreg \
            --ngram_max 2 \
            --class_weight balanced \
            --stopwords_path "" \
            --calibration none \
            --test_size 0.5

          cp -f models/model_logreg.joblib models/model_best.joblib || true
          test -f models/model_best.joblib
          test -f models/label_encoder.joblib

      - name: Lint
        run: |
          flake8 src

      - name: Tests
        run: |
          pytest -q -vv

      - name: Smoke API
        run: |
          . .venv/bin/activate
          uvicorn api.main:app --host 127.0.0.1 --port 8000 &
          PID=$!
          sleep 2
          curl -s http://127.0.0.1:8000/health || true
          curl -s -X POST http://127.0.0.1:8000/predict -H 'Content-Type: application/json' -d '{"text":"great hotel"}'
          kill $PID || true


  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t sentiment-app:ci .
